src/agent.rs
src/avoidance.rs
src/island.rs
src/lib.rs
src/nav_data.rs
src/nav_mesh.rs
src/path.rs
src/pathfinding.rs
src/util.rs

Fixes #3 and partially fixes #2.
We still have no support for moving between meshes, but that will come with #7.

Create Islands to support multiple nav meshes in one Archipelago.

---

src/lib.rs

Make Island and IslandId public.

---

src/lib.rs

Mark islands clean during update.

---

src/debug.rs
src/lib.rs

Now users can see what's going on!

Create a trait to visualize the Archipelago data.

---

src/agent.rs
src/lib.rs

Add `AgentState` to `Agent` to report the state of the agent to users.

---

Cargo.toml

I also updated some dependencies.

Bump version to 0.2.0.

---

src/nav_data.rs

DisjointSet is not Sync due to holding Cells, so we have to workaround this by using a Mutex. This should be fine since we only lock the mutex whenever we do pathfinding and only for a short time to figure out whether the regions are connected.
If in the future we find the mutex being slow, we can even move the locking of the mutex outside of the pathfinding call to only lock once per frame (excluding updating the set).

Fix Archipelago not being Sync.

---

crates/bevy_landmass/src/landmass_structs.rs
crates/bevy_landmass/src/lib.rs
crates/bevy_landmass/src/nav_mesh.rs
crates/bevy_landmass/src/util.rs

Some of the docs could maybe use some work but at least we've got some now!

Add docs for pretty much everything in `bevy_landmass`.

---

crates/bevy_landmass/example/main.rs
crates/bevy_landmass/src/lib.rs
crates/bevy_landmass/src/lib_test.rs

Now `bevy_landmass` users can add characters!
Fixes #43.

Add `Character` support to `bevy_landmass`.

---

crates/bevy_landmass/src/debug.rs
crates/landmass/src/debug.rs
crates/landmass/src/debug_test.rs

Now boundary links are drawn in green. This is useful for my own debugging.

Allow debug drawing to draw boundary links.

---

crates/landmass/src/astar.rs
crates/landmass/src/astar_test.rs
crates/landmass/src/lib.rs
crates/landmass/src/pathfinding.rs
crates/landmass/src/pathfinding_test.rs

This is not a behaviour change, just a slight refactor.

Refactor pathing slightly to clean it up.

---

crates/bevy_landmass/Cargo.toml
crates/bevy_landmass/README.md
crates/bevy_landmass/example/main.rs
crates/bevy_landmass/src/debug.rs
crates/bevy_landmass/src/lib.rs
crates/bevy_landmass/src/lib_test.rs

A new Bevy version just dropped! Now's a good time to publish these crates!

Bump Bevy to 0.14.

---

crates/bevy_landmass/README.md
crates/bevy_landmass/src/lib_test.rs
crates/bevy_landmass/src/nav_mesh.rs
crates/bevy_landmass/src/nav_mesh_test.rs
crates/bevy_landmass/src/util.rs
crates/landmass/README.md
crates/landmass/src/agent_test.rs
crates/landmass/src/avoidance.rs
crates/landmass/src/avoidance_test.rs
crates/landmass/src/debug_test.rs
crates/landmass/src/lib_test.rs
crates/landmass/src/nav_data.rs
crates/landmass/src/nav_data_test.rs
crates/landmass/src/nav_mesh.rs
crates/landmass/src/nav_mesh_test.rs
crates/landmass/src/path.rs
crates/landmass/src/path_test.rs
crates/landmass/src/pathfinding_test.rs
crates/landmass/src/util.rs
crates/landmass/src/util_test.rs

Fixes #62.
Now our coordinate system makes a lot more sense! Counter-clockwise is actually counter clockwise!

Fix the coordinate system used by landmass.

---

crates/landmass/src/lib.rs
crates/landmass/src/lib_test.rs
crates/landmass/src/query.rs
crates/landmass/src/query_test.rs

Add support for finding paths adhoc.

---

crates/bevy_landmass/src/agent.rs
crates/bevy_landmass/src/character.rs
crates/bevy_landmass/src/island.rs
crates/bevy_landmass/src/lib.rs
crates/bevy_landmass/src/lib_test.rs

Previously, most of the stuff was in `lib.rs`. Now it's spread between a few reasonably named files. Much more comprehensible!

Split up `bevy_landmass` into a more sensible file structure.

---

crates/bevy_landmass/README.md
crates/bevy_landmass/example/main.rs
crates/bevy_landmass/src/agent.rs
crates/bevy_landmass/src/lib_test.rs
crates/landmass/README.md
crates/landmass/src/agent.rs
crates/landmass/src/agent_test.rs
crates/landmass/src/avoidance.rs
crates/landmass/src/avoidance_test.rs
crates/landmass/src/debug_test.rs
crates/landmass/src/lib.rs
crates/landmass/src/lib_test.rs

Allow setting the "desired speed" of agents independently of the "max speed".

---

crates/bevy_landmass/Cargo.toml
crates/landmass/Cargo.toml

This is pretty much the release!

Bump the versions of landmass and bevy_landmass.

---

crates/bevy_landmass/Cargo.toml
crates/bevy_landmass/README.md
crates/landmass/README.md
crates/landmass/src/nav_data.rs
crates/landmass_oxidized_navigation/Cargo.toml

Fix colliding example names and accidental pub on non-reexported type.

---

crates/bevy_landmass/Cargo.toml
crates/bevy_landmass/example/main.rs
crates/bevy_landmass/src/agent.rs
crates/bevy_landmass/src/character.rs
crates/bevy_landmass/src/coords.rs
crates/bevy_landmass/src/debug.rs
crates/bevy_landmass/src/debug_test.rs
crates/bevy_landmass/src/island.rs
crates/bevy_landmass/src/landmass_structs.rs
crates/bevy_landmass/src/lib.rs
crates/bevy_landmass/src/lib_test.rs
crates/bevy_landmass/src/nav_mesh.rs
crates/bevy_landmass/src/nav_mesh_test.rs
crates/landmass/Cargo.toml
crates/landmass_oxidized_navigation/Cargo.toml

As part of this, I'm only depending on the necessary subcrates of `bevy`.

Bump Bevy to 0.16.0-rc.1.

---

.github/codecov.yml

I generally don't care how covered my tests are, just my actual code.

Make codecov ignore test file changes.

---

crates/landmass/src/debug_test.rs

Regaining some test coverage after #150 and #129.

Improve testing of `landmass::debug`.

---

CHANGELOG.md
crates/bevy_landmass/README.md
crates/bevy_landmass/src/debug.rs
crates/bevy_landmass/src/lib.rs
crates/landmass_rerecast/src/lib.rs

Rename `LandmassSystemSet` to `LandmassSystems`.
