- src/agent.rs
- src/avoidance.rs
- src/island.rs
- src/lib.rs
- src/nav_data.rs
- src/path.rs
- src/pathfinding.rs
It sucks that we have to use Arcs, but this is an easy way to allow us to compare nav meshes, and allows callers to keep their own copy to check for deltas.
> Pass ValidNavigationMesh to Islands as Arcs.

- src/island.rs
- src/nav_mesh.rs
- src/util.rs
Previously, linkable edges were computed in local space against world space region bounds. Now the linkable edges are transformed to world space before testing against the world space region bounds.
Regardless, these linkable edges are yet to be used. But they will be as part of #7.
> Fix linkable edges being computed incorrectly.

- src/agent.rs
- src/avoidance.rs
- src/debug.rs
- src/island.rs
- src/lib.rs
- src/nav_data.rs
- src/path.rs
- src/pathfinding.rs
Now islands don't need to care about what they're "responsible" for. We also don't need to specify the linkable_distance_to_region_edge per island - we can do it once for the entire Archipelago (which makes more sense).
> Simplify creating islands

- src/agent.rs
- src/lib.rs
Now we can differentiate there being no path vs not even starting the search due to no start/end node!
> Add `AgentNotOnNavMesh` and `TargetNotOnNavMesh`.

- src/avoidance.rs
- src/debug.rs
- src/lib_test.rs
- src/nav_data.rs
- src/nav_data_test.rs
- src/nav_mesh.rs
- src/nav_mesh_test.rs
- src/pathfinding.rs
Previously:
- Connectivity and boundary links had to have their cost recomputed during pathfinding (including repeatedly travelling across the same edge/link).
- To know whether an edge was connected or not, you had to iterate through the connectivity.
Now:
- Connectivity and boundary links compute their cost during nav mesh validation and island linking respectively. This means pathfinding should be much faster since we don't have to recompute those costs all the time.
- Connectivity is stored per-edge in the polygons. This makes it easy to lookup whether an edge is connected or not, though at the cost of potentially higher memory usage (this should be fairly small).
> Improve the performance and structure of connectivity data.

- src/lib.rs
- src/lib_test.rs
Fixes #8.
This isn't zero-cost. We could instead make this some sort of callback, but that would end up with mutexes and stuff in user code which is sad. I think this is a fine v1. We can always rework it in the future!
> Add a way to get the pathing results from the last update call.

- .github/workflows/test.yml
- src/astar.rs
- src/avoidance.rs
- src/lib.rs
- src/nav_data.rs
- src/path.rs
- src/pathfinding.rs
Now pull requests will automatically determine if they satisfy clippy and rustfmt! I also fixed up all the clippy warnings so we're all green.
> Add clippy and format Github Actions.

- README.md
- src/agent.rs
- src/agent_test.rs
- src/avoidance.rs
- src/avoidance_test.rs
- src/character.rs
- src/lib.rs
- src/lib_test.rs
Previously, there was no good way to represent non-AI characters. You maybe could have made an agent that never had a target, but this was hacky at best. Now we have proper support for non-AI characters. Users just need to add characters using `Archipelago::add_character` and then keep their position/velocity updated. AI characters will then avoid these characters.
Fixes #9.
> Add support for non-AI controlled characters.

- crates/landmass/Cargo.toml
- crates/landmass/src/nav_data.rs
- crates/landmass/src/nav_data_test.rs
- crates/landmass/src/util.rs
Previously no polygons or vertices would just crash. Now these nav meshes are ignored. We could call empty nav meshes invalid (and check for this in `NavigationMesh::validate`). I am still on the fence about that, so for now we are just gonna fix it and move on.
Also bumped the dodgy version.
> Fix a crash when creating nav meshes with no polygons or vertices.

- crates/bevy_landmass/Cargo.toml
- crates/landmass/Cargo.toml
I am not publishing these crates yet, I want to make sure I can upgrade to Bevy 0.14 first.
> Bump the version of bevy_landmass and landmass.

- crates/landmass/src/astar.rs
- crates/landmass/src/geometry.rs
- crates/landmass/src/island.rs
- crates/landmass/src/lib.rs
- crates/landmass/src/lib_test.rs
- crates/landmass/src/nav_data.rs
- crates/landmass/src/nav_mesh.rs
- crates/landmass/src/path.rs
- crates/landmass/src/util.rs
- crates/landmass/src/util_test.rs
This prevents types and functions from accidentally being made public, and makes it more clear the intent of different types.
I was also able to track down some types that no longer need to be public at all!
> Switch the visibility of all internal types to `pub(crate)`.

- crates/landmass/src/coords.rs
- crates/landmass/src/lib.rs
- crates/landmass/src/lib_test.rs
- crates/landmass/src/query.rs
- crates/landmass/src/query_test.rs
Now users can find points on the archipelago for their own uses!
For a concrete example of this: I have a game where I allow players to place objects, and these objects have a handful of "target points" around each object. I want my AI characters to randomly select one of these target points for an object and go there to interact with the object. However if the player places objects really close together, those points may be off the nav mesh. So I want to filter the target points based on whether they are on the nav mesh or not, hence this function.
> Add `sample_point` to `Archipelago`.

- crates/bevy_landmass/README.md
- crates/bevy_landmass/example/main.rs
- crates/bevy_landmass/src/lib.rs
- crates/bevy_landmass/src/lib_test.rs
- crates/bevy_landmass/src/nav_mesh.rs
- crates/landmass/README.md
- crates/landmass/src/agent.rs
- crates/landmass/src/agent_test.rs
- crates/landmass/src/avoidance_test.rs
- crates/landmass/src/debug_test.rs
- crates/landmass/src/island.rs
- crates/landmass/src/lib.rs
- crates/landmass/src/lib_test.rs
- crates/landmass/src/nav_data.rs
- crates/landmass/src/nav_data_test.rs
- crates/landmass/src/nav_mesh.rs
- crates/landmass/src/nav_mesh_test.rs
- crates/landmass/src/path_test.rs
- crates/landmass/src/pathfinding.rs
- crates/landmass/src/pathfinding_test.rs
- crates/landmass/src/query.rs
- crates/landmass/src/query_test.rs
This allows users to have some areas take longer to navigate, and having the pathfinding algorithm avoid these regions. Similarly, some nodes may be faster to navigate and so should be preferred.
* Every `NavigationMesh` records a "type index" for each polygon. This is propagated to the `Polygon`s in `ValidNavigationMesh`.
* When adding a navigation mesh to an island, you also have to specify a map from the type indices to the actual node type.
* Node types are created in the archipelago.
* You can change the cost of node types at runtime, and even assign "override node type costs" to agents.
> Add support for "node types" with differing costs.

- crates/bevy_landmass/src/island.rs
- crates/bevy_landmass/src/lib.rs
- crates/bevy_landmass/src/lib_test.rs
- crates/landmass/README.md
- crates/landmass/src/agent_test.rs
- crates/landmass/src/avoidance.rs
- crates/landmass/src/avoidance_test.rs
- crates/landmass/src/debug.rs
- crates/landmass/src/debug_test.rs
- crates/landmass/src/island.rs
- crates/landmass/src/lib.rs
- crates/landmass/src/lib_test.rs
- crates/landmass/src/nav_data.rs
- crates/landmass/src/nav_data_test.rs
- crates/landmass/src/path.rs
- crates/landmass/src/path_test.rs
- crates/landmass/src/pathfinding.rs
- crates/landmass/src/pathfinding_test.rs
- crates/landmass/src/query_test.rs
Fixes #72.
Now clearing a nav mesh is just removing a nav mesh! We use to have empty islands a long time ago to support a "region" of interest for each island. Now islands don't have this so we can just make them live wherever the nav mesh is.
> Make islands transient.

- crates/bevy_landmass/example/main.rs
Now the center of one of the nav meshes is a slow path, and we can spawn agents that can take the fast path.
I also added a message to explain the keybinds.
> Improve the bevy_landmass example to include an example of a "slow path".

- crates/bevy_landmass/src/island.rs
- crates/bevy_landmass/src/lib.rs
- crates/bevy_landmass/src/lib_test.rs
- crates/landmass/src/query.rs
- crates/landmass/src/query_test.rs
For landmass: `SampledPoint` now reports its island and its node type!
For bevy_landmass: we actually have a query API! It looks a lot like landmass :)
> Improve the querying API in both landmass and bevy_landmass.

- crates/bevy_landmass/Cargo.toml
- crates/landmass/Cargo.toml
Now we can't accidentally confuse the last version for the new version!
> Add a dev suffix and bump the version.

- crates/landmass_oxidized_navigation/Cargo.toml
This matches the other crates in this repo!
> Bump landmass_oxidized_navigation to 0.2.0-dev.

- crates/landmass_oxidized_navigation/Cargo.toml
I forgot to update this dependency when I bumped the version to 0.2.0-dev.
> Fix the dependency on bevy_landmass to use 0.8.0-dev for landmass_oxidized_navigation.

- crates/landmass/src/avoidance.rs
- crates/landmass/src/avoidance_test.rs
- crates/landmass/src/lib.rs
Previously, agents who have reached their target would still move out of the way a lot. Now this is less so. Note agents will still move out of the way if it resolves a collision, but they will prefer to move a lot less.
> Add a way for agents to have less avoidance responsibility once they reach their destination.

- crates/bevy_landmass/Cargo.toml
- crates/bevy_landmass/README.md
- crates/bevy_landmass/example/main.rs
- crates/bevy_landmass/src/agent.rs
- crates/bevy_landmass/src/character.rs
- crates/bevy_landmass/src/debug.rs
- crates/bevy_landmass/src/island.rs
- crates/bevy_landmass/src/lib.rs
- crates/bevy_landmass/src/lib_test.rs
- crates/landmass_oxidized_navigation/Cargo.toml
Now we're (mostly) ready for Bevy 0.15.0! The exception is `landmass_oxidized_navigation`, which needs to wait for `oxidized_navigation`, which itself needs to wait for `rapier` and `avian`.
There's stuff I want to do before we release the new version (to also release a new `landmass` version).
> Upgrade Bevy to 0.15.0-rc.2.

- crates/bevy_landmass/README.md
- crates/bevy_landmass/example/main.rs
- crates/bevy_landmass/src/lib.rs
- crates/bevy_landmass/src/lib_test.rs
- crates/landmass/README.md
- crates/landmass/src/agent_test.rs
- crates/landmass/src/avoidance_test.rs
- crates/landmass/src/debug_test.rs
- crates/landmass/src/lib.rs
- crates/landmass/src/lib_test.rs
- crates/landmass/src/nav_data_test.rs
- crates/landmass/src/path_test.rs
- crates/landmass/src/pathfinding_test.rs
- crates/landmass/src/query_test.rs
Previously, the `AgentOptions` were arbitrary defaults. The is unfortunate for cases where agents don't have a radius near 1. For example, in 2D cases, agents may be ~100px in size. This makes the default neighbourhood 5px, which results in very strange behaviour. Now, users have to explicitly pass in the `AgentOptions`, and there is no default, only a default constructor that takes in the agent's radius.
> Make `Archipelago::new` take an `AgentOptions`.

- crates/bevy_landmass/src/agent.rs
- crates/bevy_landmass/src/character.rs
- crates/bevy_landmass/src/island.rs
- crates/bevy_landmass/src/lib_test.rs
The unfortunate part is we have to recompute this every frame for each such entity. But at least now we sync up faster!
> Use `TransformHelper` to sync agents, characters, and islands.

- crates/bevy_landmass/src/agent.rs
- crates/bevy_landmass/src/debug.rs
- crates/bevy_landmass/src/debug_test.rs
- crates/bevy_landmass/src/lib.rs
- crates/bevy_landmass/src/lib_test.rs
Previously we were just re-exporting the debug types from `landmass` in `bevy_landmass`. However this references agents with `AgentId`. The agent ID of agents in `bevy_landmass` are not exposed, so this is not usable.
This PR creates duplicates of `landmass` debug types which convert everything to entities through an adapter. I've also added a test that at least one of these are correct.
> Make debug drawing in `bevy_landmass` expose entities instead of agent IDs.

- crates/bevy_landmass/Cargo.toml
- crates/bevy_landmass/src/agent.rs
- crates/bevy_landmass/src/debug.rs
- crates/bevy_landmass/src/debug_test.rs
- crates/bevy_landmass/src/lib_test.rs
- crates/landmass/Cargo.toml
- crates/landmass/src/agent.rs
- crates/landmass/src/avoidance.rs
- crates/landmass/src/debug.rs
- crates/landmass/src/debug_test.rs
This gives more visualization tools for `landmass` and `bevy_landmass`.
> Add a way to visualize `dodgy_2d` avoidance data for agents.

- crates/bevy_landmass/src/lib.rs
- crates/landmass/src/avoidance.rs
- crates/landmass/src/avoidance_test.rs
This lets us get avoidance data even when we freeze time.
> Allow passing in a delta time of 0.0.

- crates/bevy_landmass/src/lib.rs
- crates/landmass_oxidized_navigation/example/main.rs
- crates/landmass_oxidized_navigation/src/lib.rs
- crates/landmass_oxidized_navigation/src/lib_test.rs
Previously, we ran the navigation logic in `Update` - this occurs after `FixedUpdate` which is where physics movement (usually) occurs. Ideally we'd like to integrate as many changes and assign the most up-to-date desired movement *before* FixedUpdate. Putting it in `RunFixedMainLoop` allows us to do this.
In addition, this PR allows users to configure the scedule if that is not desirable. This does mean they will have an extraneous system set dependency in another schedule, but practically this won't matter.
> Make the schedule configurable and change the default to RunFixedMainLoop

- crates/bevy_landmass/README.md
- crates/bevy_landmass/example/main.rs
- crates/bevy_landmass/src/coords.rs
- crates/bevy_landmass/src/debug_test.rs
- crates/bevy_landmass/src/lib.rs
- crates/bevy_landmass/src/lib_test.rs
- crates/landmass/README.md
- crates/landmass/src/agent_test.rs
- crates/landmass/src/avoidance.rs
- crates/landmass/src/avoidance_test.rs
- crates/landmass/src/coords.rs
- crates/landmass/src/debug.rs
- crates/landmass/src/debug_test.rs
- crates/landmass/src/lib.rs
- crates/landmass/src/lib_test.rs
- crates/landmass/src/nav_data.rs
- crates/landmass/src/nav_data_test.rs
- crates/landmass/src/nav_mesh.rs
- crates/landmass/src/nav_mesh_test.rs
- crates/landmass/src/path_test.rs
- crates/landmass/src/pathfinding_test.rs
- crates/landmass/src/query.rs
- crates/landmass/src/query_test.rs
- crates/landmass/src/util.rs
- crates/landmass_oxidized_navigation/example/main.rs
- crates/landmass_oxidized_navigation/src/lib_test.rs
Before we only had one option for changing the sampling - the max distance that a point can be to be sampled. While this worked ok for agents walking from their feet, agents walking from their center of mass could easily sample the wrong point. Similarly, agents going upstairs/downstairs could get confused where it is.
Now, we can filter nodes by their horizontal and vertical distances separately! This means we can have a very small horizontal distance but a large vertical distance - making it much more likely that the nearest point is filtered to ones at the agent's feet. Along these lines, we can also specify how much to prefer vertical distance vs horizontal distance. This means we can prefer entirely vertical points compared to entirely horizontal points, which makes it more likely we …
> Replace the `node_sample_distance` with a more expressive sampling options struct for 3D.

- crates/landmass/src/lib.rs
The local collision avoidance ignores the vertical component, so when we normalize we were throwing away length of the vector, resulting in slowdowns. Now agents go full throttle!
> Flatten the desired_move to 2D before normalizing.

- crates/landmass/src/query.rs
- crates/landmass/src/query_test.rs
Previously, we would bail out early if the start and end point are in the same polygon. Now, we explicitly check for this case and handle it properly.
> Make sure that paths found by `Archipelago::find_path` always includes the end node.

- .github/workflows/test.yml
- crates/landmass/Cargo.toml
- crates/landmass/src/pathfinding.rs
- crates/landmass/src/util.rs
`ord_subset` has some bug on nightly. Rather than fix it or replacing it with another dep, I decided to just implement my own version of ordered floats. It's annoying I have to do this (I wish Rust exposed ordered floats directly), but there's no reason to add more dependencies for ~50 lines of code.
Fixes #126.
> Replace `ord_subset::OrdVar` with our own implementation.

- crates/landmass/src/avoidance_test.rs
This test was flaky seemingly because of some floating point inaccuracy. I don't really understand how that could be non-deterministic, but whatever. The solution is to just move the agent further from the corner that is causing the agent to slow down.
An alternative solution could be to adjust the agent's velocity, but I'd rather not do that.
> Fix a flake in `switching_nav_mesh_to_fewer_vertices_does_not_result_in_panic` test.

- crates/bevy_landmass/src/coords.rs
- crates/bevy_landmass/src/debug_test.rs
- crates/bevy_landmass/src/lib_test.rs
- crates/landmass/src/coords.rs
- crates/landmass/src/nav_mesh.rs
- crates/landmass/src/nav_mesh_test.rs
Previously, if your coordinate system did something "weird" while converting coordinates, CCW polygons would become CW, meaning you would need to create your nav meshes CW in order for them to be flipped during the conversion into CCW polygons.
Now, coordinate systems can say they are flipped to automatically flip the polygons so your nav meshes can be CCW and stay CCW in landmass.
> Allow coordinate systems to specify how they should be flipped to be CCW.

- crates/landmass/src/agent_test.rs
- crates/landmass/src/debug.rs
- crates/landmass/src/debug_test.rs
- crates/landmass/src/path.rs
- crates/landmass/src/path_test.rs
- crates/landmass/src/pathfinding.rs
- crates/landmass/src/pathfinding_test.rs
Since #124, we no longer navigate through the center of nodes. Instead we navigate through the center of edges.
Unfortunately the debug view hasn't kept up with that. In a sense it was still "correct" - it was rendering the corridor - not the path. However I think that vis poorly communicates the path the agent is trying to travel, and I think the more important thing to communicate is what the agent "was thinking" when they planned their path. So I'm now drawing the corridor through the center of edges.
Here's a before:
And here's an after:
> Make debug rendering of paths actually match how they are computed.

- .github/workflows/test.yml
- CHANGELOG.md
- crates/bevy_landmass/README.md
- crates/bevy_landmass/examples/basic.rs
- crates/bevy_landmass/src/agent.rs
- crates/bevy_landmass/src/debug_test.rs
- crates/bevy_landmass/src/island.rs
- crates/bevy_landmass/src/lib.rs
- crates/bevy_landmass/src/lib_test.rs
- crates/landmass/README.md
- crates/landmass/src/agent.rs
- crates/landmass/src/agent_test.rs
- crates/landmass/src/avoidance_test.rs
- crates/landmass/src/debug_test.rs
- crates/landmass/src/island.rs
- crates/landmass/src/lib.rs
- crates/landmass/src/lib_test.rs
- crates/landmass/src/nav_data.rs
- crates/landmass/src/nav_data_test.rs
- crates/landmass/src/path_test.rs
- crates/landmass/src/pathfinding.rs
- crates/landmass/src/pathfinding_test.rs
- crates/landmass/src/query.rs
- crates/landmass/src/query_test.rs
Previously, nav meshes had a type index for each polygon, which then got translated into a node type (which could only be created on the archipelago), which then got translated into the final cost. This was a pain in the neck to deal with, since you couldn't just load up a nav mesh, you had to "glue" it with the correct node types.
In practice, users are likely going to be good enough enforcing the semantics of each type index (e.g., 1 is grass, 2 is road, 3 is quicksand). Then the API on the users is much simpler - just specify the cost of each type index! This can even be done at load time very easily.
In practice, navigation systems in other engines just use a simple integer to represent the different areas (though usually this is represented as an enum that can be configured).
> Replace node types with just directly using the type index.

- crates/bevy_landmass/examples/playground.rs
Small improvement to the playground example.
> Use a smaller radius for the agents in the playground example.

- .github/workflows/test.yml
I believe this error is fixed now, so best to get back to updated nightly.
> Re-enable up-to-date nightly.

- crates/landmass/README.md
- crates/landmass/src/lib.rs
Too high values can result in agents taking strange paths when a more direct path is valid. This is visible in the playground example, so it seems like it would happen commonly.
Agents still take slightly strange paths, but much less so!
> Decrease the default avoidance time horizons.

- crates/landmass/src/agent.rs
- crates/landmass/src/agent_test.rs
- crates/landmass/src/lib.rs
Previously, this could cause agents not centered on their feet to oscillate (aka "yoyo") on their target because the agent's position isn't on the target.
> Use the agent's sampled position when deciding if the agent has reached their target.
